name: Deploy static site to S3
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIARC7MAQWHUUK2ZMDQ }}
          aws-secret-access-key: ${{ secrets.B+bUCWFwqQzQw/sxlk849jOZSoZT+4X4Y8UR2Zgb }}
          aws-region: ${{ secrets.eu-west-2 }}

      - name: Sync to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"
